magellan/models.py
from django.db import models
from django.contrib import admin
import os
from django.conf import settings
from django.utils.encoding import force_unicode
from django.utils import importlib
from django import forms
import hashlib
from collections import defaultdict
from extractor import BaseExtractor


class SpiderProfile(models.Model):
    """
    Represents a site to spider.
    """
    name = models.CharField(max_length=255)
    base_url = models.CharField(max_length=255, help_text="Full URL to page to begin spidering")
    domain = models.CharField(max_length=255, help_text="Substring (of domain or otherwise) to limit links followed", blank=True)
    depth = models.IntegerField(default=0, help_text="How many pages deep to follow links; 0 for infinite")
    active = models.BooleanField(default=True)
    timeout = models.IntegerField(default=30, help_text="Maximum time, per page, to wait for a response")
    login_url = models.CharField(max_length=255, 
                                 help_text="URL to POST credentials to; not the login form itself, but the action of the form",
                                 blank=True)
    login_details = models.CharField(max_length=255,
                                     help_text="urlencoded data to post to URL; e.g. name=foo&password=bar",
                                     blank=True)
    logged_out_string = models.CharField(max_length=255,
                                         help_text="String to search for on response page to detect logged out status",
                                         blank=True)
    threads = models.IntegerField(default=1, 
                                  help_text="How many threads to use when spidering this site")
    delay = models.IntegerField(default=0, 
                                help_text="How long to wait between requests, for each thread")    
    links_ignore_regex = models.CharField(max_length=255,
                                          help_text="Links matching this regex will not be followed",
                                          blank=True)
    extraction_plugin = models.CharField(max_length=255,
                                         help_text="Module name containing an implementation of BaseExtractor with same name as module.",
                                         blank=True)
    
    def get_extractor_class(self):
        """
        Dynamically imports a the module+class specified by extraction_plugin and returns an instance of it.
        Or returns the BaseExtractor, if none is set.
        """
        if not self.extraction_plugin:
            return BaseExtractor
        
        module_name = settings.MAGELLAN_PLUGINS_MODULE_PATH
        module = importlib.import_module(name=module_name)
        cls = getattr(module, self.extraction_plugin)
        return cls
        
    def __unicode__(self):
        return u"%s - starting at: %s" % (self.name, self.base_url)

class SpiderProfileAdminForm(forms.ModelForm):
    class Meta:
        model = SpiderProfile
        widgets = {
                   'login_details': forms.TextInput(attrs={'size': '3'})
                   }

class SpiderProfileAdmin(admin.ModelAdmin):
    form = SpiderProfileAdminForm

admin.site.register(SpiderProfile, SpiderProfileAdmin)
        
            

            
    
        





        


    

magellan/management/__init__.py
from django.db.models.signals import post_syncdb
from django.db.models import get_models
import magellan.models



def fix_profile_key_field(sender, **kwargs):
    """
    Lame fix for django's sqlite support being mostly borked re: autoincrement fields;
    this could be genericized to handle all models in the module, but for now I'm just doing
    this the hacky way.
    """
    from django.db import connection, transaction
    if 'sqlite' not in connection.settings_dict['ENGINE']:
        return
    cursor = connection.cursor()
    table_name = magellan.models.SpiderProfile._meta.db_table
    
    res = cursor.execute("select sql from sqlite_master where name = '%s'" % table_name)
    schema = res.fetchone()[0]
    if 'PRIMARY KEY' in schema:
        return #already done
    
    #drop the old table
    cursor.execute("drop table %s" % table_name)

#    #rename the table
#    tmp_table_name = "tmp_table_for_spiderprofile"
#    cursor.execute('ALTER TABLE "%s" RENAME TO "%s"' % (table_name, tmp_table_name))
#    
    #create new table with correct schema
    new_schema = schema.replace('"id" INTEGER NOT NULL,', '"id" INTEGER PRIMARY KEY,')
    cursor.execute(new_schema)
    
    
    
post_syncdb.connect(fix_profile_key_field, sender=magellan.models)

magellan/views.py
from django import forms
from django.conf import settings
from whoosh import index, store, fields
from django.shortcuts import render
from magellan.utils import get_backend
from magellan.models import SpiderProfile
from datetime import datetime

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)
    profiles = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple)
    
    def __init__(self, *args, **kwargs):
        profiles = SpiderProfile.objects.filter(active=True)
        profile_choices = [(p.pk, p.name) for p in profiles]
        self.base_fields['profiles'].choices = profile_choices
        self.base_fields['profiles'].initial = [p[0] for p in profile_choices]
        super(SearchForm, self).__init__(*args, **kwargs)
        


def search(request):
    vars = {}
    if request.GET.get('query'):
        #form was submitted
        page = int(request.GET.get('page', 1))
        per_page = int(request.GET.get('per_page', 100))
        search_form = SearchForm(request.GET)
        query = search_form['query'].value().replace('+', ' AND ').replace(' -', ' NOT ')
        profile_ids = search_form['profiles'].value()
        if profile_ids and len(profile_ids) != len(search_form['profiles'].field.choices):
            profiles = SpiderProfile.objects.filter(active=True).filter(pk__in=profile_ids)
            profile_names = [profile.name for profile in profiles]
        else:
            profile_names = None
        
        backend = get_backend()
        start_time = datetime.now()
        results = backend.search(query, pagenum=page, pagelen=per_page, sites=profile_names)
        query_time = datetime.now() - start_time
        query_time_formatted = float(query_time.seconds) + float(query_time.microseconds)/100000.0 
        vars['query_time'] = query_time_formatted
        vars['page'] = page
        vars['pagecount'] = results['pagecount']
        vars['results'] = results['hits']
        vars['num_results'] = results['total_hits']
        vars['pagination_results'] = range(1, vars['num_results']+1)
        vars['start'] = (page-1)*per_page + 1
        template = 'search_results.html'
    else:
        search_form = SearchForm()
        template = 'index.html'
    
    vars['search_form'] = search_form 
    return render(request, template, vars)

magellan/templates/index.html
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>Magellan :: Search</title>
    <link href="{{STATIC_URL}}magellan.css" rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_query').first().focus();
        });
    </script>
  </head>
  <body>
    <div id="search_container" class="logo_bg">
        <div id="search_ui">
        {% include "search_form.html" %}
        </div> <!-- search_ui -->
    </div> <!-- search_container -->
    
    {% include "search_footer.html" %}
  </body>
</html>

magellan/templates/search_footer.html
    <ul id="tech_bugs">
        <li><a href="https://bitbucket.org/mchaput/whoosh/wiki/Home"><img alt="Whoosh!" src="{{STATIC_URL}}whoosh.png" width="80" height="28" /></a></li>
        <li><a href="http://www.djangoproject.com/"><img alt="Django" src="{{STATIC_URL}}django.png" width="80" height="28" /></a></li>
        <li><a href="http://www.python.org/"><img alt="Python" src="{{STATIC_URL}}python.png" width="80" height="25" /></a></li>
    </ul> <!-- tech_bugs -->

magellan/templates/search_form.html
<form action="" method="get" name="search_form" class="search_form">
    {{ search_form.non_field_errors }}
    {{search_form.query}} {{search_form.query.errors}}
    <input type="submit" value="Go >" />
    
    {{search_form.profiles}} {{search_form.profiles.errors}}
</form>

magellan/templates/search_results.html
{% load pagination_tags %}
{% autopaginate pagination_results 100 %}

<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>Magellan :: Results</title>
    <link href="{{STATIC_URL}}magellan.css" rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_query').first().focus();
        });
    </script>
  </head>
  <body>
    <div id="results_search_container" class="logo_bg">
        <div id="search_ui">
            {% include "search_form.html" %}
        </div> <!-- search_ui -->
    </div> <!-- search_container -->
    
    
    
    <p class="results_stats">Found {{num_results}} links in {{query_time}} seconds. Showing page {{page}} of {{pagecount}}.</p>
    {% paginate %}

    <ol id="results_list" start="{{start}}">
    	<!-- <span class="search_term">blah</span> will highlight words here -->
    	{% for hit in results %}
        <li>
            <p class="result_title"><a href="{{ hit.url }}">{{ hit.title }}</a></p>
            <p class="result_excerpt">
            	{% autoescape off %}{{hit.highlight}}{% endautoescape %}
            </p>
	    <p class='result_score'>
		Score: {{hit.score}}
	    </p>
            <p class="result_link"><a href="{{ hit.url }}">{{ hit.url }}</a></p>
        </li>
        {% endfor %}
    </ol> <!-- results_list -->
        
        
    {% paginate %}

    <div id="search_ui_bottom">
    	{% include "search_form.html" %}
    </div> <!-- search_ui_bottom -->

    {% include "search_footer.html" %}
    
  </body>
</html>